### ISSUE TITLE
Fix footer and nav

### ISSUE THREAD

**Issue by AlexandraOM** [fac18/chefup_app#113]
- [x] remove nav bar from home header
- [x] move about us to footer
- [x] fix footer to bottom as you scroll

**Comment by marialani** [comment]
the footer should already be fixed to the bottom of the screen if not there may be css conflicts

**Comment by AlexandraOM** [comment]
Yep! We started adding issues before we found your pull request!

**Comment by AlexandraOM** [comment]
relates #116
