### ISSUE TITLE
Running tests twice

### ISSUE THREAD

**Issue by samhstn** [fac18/chefup_app#78]
I might have missed something, but it looks like your ci is running your tests twice ([here](https://github.com/fac18/chefup_app/blob/master/.travis.yml#L8-L9)).

We can replicate what travis will be running, but on our local machines by running this:

```bash
CI=true npm test
CI=true npm run coverage
```

We instead only need to run the following to run both our tests and coverage:

```bash
CI=true npm run coverage
```

To fix this, we can remove the [`npm test` line](https://github.com/fac18/chefup_app/blob/master/.travis.yml#L8) from our `.travis.yml`.

**Comment by marialani** [comment]
Thanks Sam, we've left it in the package.json but have now removed it from the travis filema
